### ISSUE TITLE
fails opening a folder

### ISSUE THREAD

**Issue by simonm3** [rkhwaja/fs.googledrivefs#24]
This fails with refresh error. It seems it is only possible to open the root folder as a filesystem.
```
gd = fs.open_fs(f"googledrive://{creds.gdrive()}/eedata")
gd.listdir("/")
```
Note that this works:
```
gd = fs.open_fs(f"googledrive://{creds.gdrive()}")
gd = gd.makedirs("eedata", recreate=True)
gd.listdir("/")
```
Also this fails saying directory exists!
```
gd = fs.open_fs(f"googledrive://{creds.gdrive()}")
gd = gd.makedir("eedata", recreate=True)
gd.listdir("/")
```

**Comment by msb** [comment]
My case is similar to @simonm3 - I have a credentials for a service account that has permission on a GCP folder. The folder would have to be referenced by a file id but it isn't clear to me how this would be done using either `fs.opendir()` or a path.

**Comment by rkhwaja** [comment]
Going by the code in your other issue, I think that the format of your URI is wrong - the "?access_token=..." part has to be at the end, after the subdirectory part.

**Comment by rkhwaja** [comment]
Is GCP is a different service? This project supports "Google Drive". There's another pyfilesystem plugin called fs-gcsfs which supports "Google Cloud Storage"

**Comment by simonm3** [comment]
@rkhwaja you may be right about the format. however this still only opens the root folder. code below lists the root folder contents.
```
gd = fs.open_fs(f"googledrive://eedata/{creds.gdrive()}")
gd.listdir("/")
```

**Comment by simonm3** [comment]
It works if I add an extra slash fs.open_fs(f"googledrive:///eedata/{creds.gdrive()}")

However the pyfilesystem url does not have a slash at the start of a folder in the examples https://docs.pyfilesystem.org/en/latest/openers.html

**Comment by simonm3** [comment]
Also the format is <protocol>://<username>:<password>@<resource>

Ideally the creds should be in similar format regardless of file system used. So for google drive API they should appear before the resource and googledrivefs should convert that into whatever format google uses.

**Comment by simonm3** [comment]
github won't let me enter the fs utl format but you can see it on the documentation https://docs.pyfilesystem.org/en/latest/openers.html

**Comment by msb** [comment]
My mistake - I should have written Google Drive folder (it's the [service account](https://cloud.google.com/iam/docs/service-accounts) that is part of the Google Clouds Platform). My use case is supported by the native Drive API - it's a method for a user to grant an application permission to work on a sub-set of the user's files.

**Comment by rkhwaja** [comment]
> My case is similar to @simonm3 - I have a credentials for a service account that has permission on a GCP folder. The folder would have to be referenced by a file id but it isn't clear to me how this would be done using either `fs.opendir()` or a path.



> My case is similar to @simonm3 - I have a credentials for a service account that has permission on a GCP folder. The folder would have to be referenced by a file id but it isn't clear to me how this would be done using either `fs.opendir()` or a path.

Since this project is a plugin for pyfilesystem2, it only uses "paths", although I suppose that the definition of that is somewhat up to the individual plugins - I'm not sure how far you can push that. We can add custom methods that do something specific with the filesystem (e.g. add_parent, remove_parent) but that aren't relevant to filesystems in general.

**Comment by msb** [comment]
Thanks for your response @rkhwaja. I have [made a fork](https://github.com/msb/fs.googledrivefs/commits/file_id_support) and implemented support for a sub-tree specified by an ID. I have also used it in (an example project)[https://github.com/msb/gitlab-download] with an explanatory readme. I've had second thoughts about the approach in the fork and think maybe the root directory could better be specified by a parameter (say `root_dir_id`) passed to the `GoogleDriveFSOpener`. If you like this idea, I'm happy to re-work and create a CR.
