### ISSUE TITLE
Shared Drive support

### ISSUE THREAD

**Issue by jvtm** [rkhwaja/fs.googledrivefs#56]
Hi,

For a project using Google Drive as one possible input source for files, we spotted that _shared drives_ are not supported.

I have a local patch that adds support for:
* `file.list`
* `file.get`
* a bit more optimized binary reads (iterator / `next_chunk()`, not logging the contents) in `openbin()` helper
* more direct `download()` which can skip creating additional local tempfile (this code path gets used by eg `copy_file()`)

So that basic functionality for iterating the filesystem and downloading / copying files (to another pyfilesystem) works.

Links:
* https://developers.google.com/drive/api/v3/enable-shareddrives
* https://docs.pyfilesystem.org/en/latest/_modules/fs/copy.html#copy_file
* https://docs.pyfilesystem.org/en/latest/reference/base.html#fs.base.FS.download

My question is, would be worth sending this patch as pull-request? Perhaps as-is (read operations, some internals ready for other operations, download optimization), or maybe checking if also the write operations work. For my use-case reading was enough.

The changes operate so that URL opener + GoogleDriveFS init accepts optional `drive_id`, and it actually works well together with also specifying `root_id` (so, a directory that exists within that shared drive).

I'm not sure how well the current tests could cover the case of a shared drive.

Note: ended up applying also some `ttl_cache` decorators to few internal methods for speedups, but that's another story :)

**Comment by rkhwaja** [comment]
Sounds great - thanks.

Can you separate the PRs by functionality? In particular, separate out the ones that aren't about shared drives. I don't think my tests will test the shared drive stuff since I don't have access to that type of account.

**Comment by jvtm** [comment]
Splitting to separate PRs makes sense. Expect some of that during next week, hopefully I have time to rebase + cleanup a little bit, perhaps try out the write actions too.

1. Shared Drive support
2. `def download()` helper using more efficient `MediaIoBaseDownload` + `next_chunk()` style reading + apply same logic to the existing code that downloads to tempfile

**Comment by jvtm** [comment]
I'll continue with the actual Shared Drive patch today. Needs a few cleanups, and I'm not sure if I'm able to easily test the creation/update calls at the moment. I might be able to setup a fully isolated drive for running full set of tests later this week. Patching the calls is easy though, but would like to see them in real action.

Basic approach is to create extra keyword argument dictionaries in GoogleDriveFS init, works well enough and no need for  huge amounts of if-else blocks in various places.

**Comment by rkhwaja** [comment]
I made a 2.1.0 release which contains this feature

**Comment by jvtm** [comment]
> I made a 2.1.0 release which contains this feature

Thanks. Seems to install and work as expected
